#USADO EM lib/asaas/utils.rb para verifica se o numero de parcelamento 'enviado-pelo select' ainda está disponível
#usado em dashboard_footer.erb 
# DISPONIVEL SOMENTE ATÉ 4 VEZES
#NÃO PODE SER DIAS DE VENCIMENTO DIFERENTES
#para ver a alteração no dashboard_footer.erb é necessário fazer uma alteração lá (saltar uma linha porx) - para compilar o arquivo dnv
vencimentos:
#---------- ALTERAR DATAS QUANDO A EMPRESA DECIDIR QUAIS SÃO -----------#

  mes1: '06/04/2018'
  mes2: '30/04/2018'
  mes3: '18/05/2018'

# SEgundo lote 
#  mes1: '21/08/2018'
#   mes2: '21/09/2018'
#   mes3: '01/01/2018'
#   mes4: '01/01/2018'
