#USADO EM lib/asaas/utils.rb para verifica se o numero de parcelamento 'enviado-pelo select' ainda está disponível
#usado em dashboard_footer.erb 
# DISPONIVEL SOMENTE ATÉ 4 VEZES
#NÃO PODE SER DIAS DE VENCIMENTO DIFERENTES
#para ver a alteração no dashboard_footer.erb é necessário fazer uma alteração lá (saltar uma linha porx) - para compilar o arquivo dnv
vencimentos:
  mes1: '22/09/2017'
  mes2: '01/01/2017'
  mes3: '01/01/2017'
  mes4: '01/01/2017'


# SEgundo lote 
#  mes1: '21/08/2017'
#   mes2: '21/09/2017'
#   mes3: '01/01/2017'
#   mes4: '01/01/2017'
